sudo: false
language: cpp
compiler: gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test # ppa:ubuntu-toolchain-r/test
    packages:
      - libbz2-dev
      - libssl-dev
      - gcc-6
      - g++-6

cache:
  directories:
    - $HOME/boost_1_64_0/boost
    - $HOME/boost_1_64_0/stage/lib

install:
  # Use GCC 5.
  - if [ "$CXX" = "g++" ]; then export CXX="g++-6" CC="gcc-6"; fi
  - export CXXFLAGS="-fPIC" CFLAGS="-fPIC"
  # Build Boost.
  - wget https://raw.githubusercontent.com/WrinklyNinja/ci-scripts/1.4.0/install_boost.py
  - python install_boost.py --directory ~ --boost-version 1.64.0 -a 64 -t gcc-6 atomic chrono date_time filesystem iostreams locale log regex system thread
  # Install packages for generating documentation
  - pip install --user -r docs/requirements.txt
  # Add sphinx-build to PATH
  - export PATH="$HOME/.local/bin:$PATH"
  # Don't install Doxygen from the repositories, it also gets the LaTeX packages
  # so is a ~ 700 MB download.
  - wget ftp://ftp.stack.nl/pub/users/dimitri/doxygen-1.8.12.linux.bin.tar.gz
  - tar -xf doxygen-1.8.12.linux.bin.tar.gz
  # Add Doxygen binary path to PATH
  - export PATH="$PWD/doxygen-1.8.12/bin:$PATH"
  # Get CMake (version available in repositories is too old, needs to be 3.1+)
  - wget --no-check-certificate https://cmake.org/files/v3.8/cmake-3.8.2-Linux-x86_64.tar.gz
  - tar -xzf cmake-3.8.2-Linux-x86_64.tar.gz
  - export PATH=$PWD/cmake-3.8.2-Linux-x86_64/bin:$PATH

before_script:
  - mkdir build
  - cd build
  # Link dynamically to the C++ standard library runtime.
  - cmake .. -DBOOST_ROOT=~/boost_1_64_0 -DBOOST_LIBRARYDIR=~/boost_1_64_0/stage/64/lib

script:
  - make all
  - ./loot_api_internals_tests
  - ./loot_api_tests

after_success:
  - cd $TRAVIS_BUILD_DIR
  - sphinx-build -b html docs build/docs/html
  - cd build
  - cpack
  - cd ..
  # Get the full repo history before trying to run git describe.
  - git fetch --unshallow
  - GIT_DESCRIBE=$(git describe --tags --long --always --abbrev=7)
  # Make copies of the archives for GitHub deployment to find.
  - cp $(ls build/package/loot_api-*.tar.xz) build/loot-api.tar.xz
  # Need to replace the Bintray config files' version placeholders.
  - sed -i "s/REPLACE_THIS_VERSION/${GIT_DESCRIBE}_${TRAVIS_BRANCH}/" scripts/travis/loot-api.bintray.json

deploy:
  - provider: bintray
    file: scripts/travis/loot-api.bintray.json
    user: wrinklyninja
    key:
      secure: "zczTW2fGiTDlrgCtDyWAcQ+FftErR8XFZ7Lz3Mnj3gbedlS7wKdpffXngpepGGQQp3N5Jt0F51mQDrRFfvgmSk0IpuSVKkzuUNt5aJEav7LYb9tho4afXGu/fd3Sj8nF0NM4rB9b2sHMKOLSBD/a+7qsf0q3W4lFZGRQPzqq6RBqB0p8brsdf4g/aoVjAGltUtagMNMYJbs5MNsZLX0Zw9pRB4bSvCf9YNXLcMckA2FQC+xiWAliMOQQlnQU5QZgzNypiTvYpyYwhLM3Xy6/QB9WkABDPEfYNcnOX7JRI81Q6QGWbbSNpDcGI1LmxDwYCftpI7ilbL+yj8Al6AFAn4Ia3AcMpoXv9De/11HYftwYL+76Lud+EaCZimy5FIj6d+GBVwiZkpnbEi8r0LJ0o9dBlLJESqSRwqhYH25fahSgfT/Tew5ftigOfJRY/sYXYXJS5TLeV7OaP6LXAivBWttB3Wo3OcE+4HsvmpgIrHGhvKsmtAQMs2ddBwKdro9jqtaCBbM2To05FtQ1/RYV2dD3v8nF7CwSX6VLp1a973CUZ5/IF3R6ONeCVwkxVqe7hPlo65NAx8L8jvxjksYIQ/r1aPhJLU7UCPPic47I/6M0fsRnT8pcRymnMcfQ5QT7h7gtqQQRJzYKaalkYVObw1ygDsqgPh5LZTf6U6S+bG8="
    skip_cleanup: true
    on:
      all_branches: true
  - provider: releases
    api_key:
      secure: "HBBghmIDgWsPq6YVrKh/M0au51ffWQdnaNr2QUFBEzsrMUgaAR04vd3eLtodHr5W2m6fJFfvIDnROYh2KnFQP0MFwEkldyToHpAJqoSxOJ2uJzq7TOiWTVlKbdnutQ+0GS0URcoM32uxRgkduWWe9McZ1mj12oyV2PKR2ojtNp9ni12O2qfzH32YPdQZ3zutxRgB82OZ0qj7HMHfD4v0yPhBncZaEWFTKKRy/LgJvaEGsEsb7u8MidRVpo/pNbNirjlh7Vlx4tm7kT2R4/ehH8H2y3MjxCaacfzaqi6LoGqMBVEjhpETI1COMvhezUdzmB/GBdX8zlTKuSs1GwiUl6FXnEPxnIU+qllx5PkHeph3GpkPZ8ChUuqnEksaBZsnVQ0D06KrivLb5otlRkfk4xfEX/68KUP7y/dNVZCVYOHSPD0N+iaKhGhTkjt77xJQ0z3U1qtoHrbtSdVUdeb+xIiyYCr8mHrQy+gNGqB8NLtpsdqWpjKh/BAcYnlu15VZLq6AASpLaDeBsCGXm/Er15z5meXDyRPtR1qT9XZgDEMXsn7ywe/dNfNxiY8sPxNn6vpqNvD7AR4s8nYm7qAm3JBw5xBaqh5HpkibIcNADkZGvDWjsbvO48/g1J5R+XT6CE77Qbj9UcYR532TbD0VSYFr6+snTf0Vwe1JgoiHNSk="
    file:
      - build/loot-api.tar.xz
    skip_cleanup: true
    on:
      repo: loot/loot-api
      tags: true

notifications:
  irc:
    channels:
      - "chat.freenode.net#loot"
    use_notice: true
    skip_join: true
