[package]
name = "libloot"
version = "0.26.0"
edition = "2024"
license = "GPL-3.0"

[dependencies]
crc32fast = "1.4.2"
fancy-regex = "0.14.0"
log = { version = "0.4.26", features = ["std"] }
petgraph = "0.8.1"
rayon = "1.10.0"
rustc-hash = "2.1.1"
saphyr = "0.0.4"
saphyr-parser = "0.0.4"
unicase = "2.8.1"

esplugin.workspace = true
libloadorder.workspace = true
loot-condition-interpreter.workspace = true

[target.'cfg(windows)'.dependencies]
windows = { version = "0.61.1", features = ["Win32_Storage_FileSystem"] }

[dev-dependencies]
rstest = "0.25.0"
rstest_reuse = "0.7.0"
tempfile = "3.17.1"

[workspace]
members = ["cxx", "ffi-errors", "nodejs", "pyo3"]

[workspace.dependencies]
esplugin = "6.1.2"
libloadorder = "18.3.0"
loot-condition-interpreter = "5.3.1"

[profile.release]
debug = "limited"

[profile.rel-with-deb-info]
inherits = "release"
opt-level = 2
debug = "limited"
