
# cargo-vet audits file

[[audits.codespan-reporting]]
who = "Oliver Hamlet <git@ortham.net>"
criteria = "safe-to-deploy"
delta = "0.12.0 -> 0.13.1"

[[audits.cxx]]
who = "Oliver Hamlet <git@ortham.net>"
criteria = "safe-to-deploy"
delta = "1.0.161 -> 1.0.192"

[[audits.cxx-build]]
who = "Oliver Hamlet <git@ortham.net>"
criteria = "safe-to-deploy"
delta = "1.0.161 -> 1.0.192"

[[audits.cxxbridge-flags]]
who = "Oliver Hamlet <git@ortham.net>"
criteria = "safe-to-deploy"
delta = "1.0.161 -> 1.0.192"

[[audits.cxxbridge-macro]]
who = "Oliver Hamlet <git@ortham.net>"
criteria = "safe-to-deploy"
delta = "1.0.161 -> 1.0.192"

[[audits.libloading]]
who = "Oliver Hamlet <git@ortham.net>"
criteria = "safe-to-deploy"
delta = "0.8.6 -> 0.8.9"
notes = "Mostly formatting changes, plus swaps windows-targets for windows-link, and adds a new function that looks fine."

[[audits.libloadorder]]
who = "Oliver Hamlet <git@ortham.net>"
criteria = "safe-to-deploy"
version = "18.5.1"
notes = "This is my own crate published using Trusted Publishing, but I can't mark it as trusted by cargo-vet because it doesn't support Trusted Publishing and just sees that the publisher is unknown."

[[audits.link-cplusplus]]
who = "Oliver Hamlet <git@ortham.net>"
criteria = "safe-to-deploy"
delta = "1.0.10 -> 1.0.12"

[[audits.loot-condition-interpreter]]
who = "Oliver Hamlet <git@ortham.net>"
criteria = "safe-to-deploy"
version = "5.3.3"
notes = "This is my own crate published using Trusted Publishing, but I can't mark it as trusted by cargo-vet because it doesn't support Trusted Publishing and just sees that the publisher is unknown."

[[audits.loot-condition-interpreter]]
who = "Oliver Hamlet <git@ortham.net>"
criteria = "safe-to-deploy"
delta = "5.3.3 -> 5.4.0"
notes = "This is my own crate published using Trusted Publishing, but I can't mark it as trusted by cargo-vet because it doesn't support Trusted Publishing and just sees that the publisher is unknown."

[[audits.rust-ini]]
who = "Oliver Hamlet <git@ortham.net>"
criteria = "safe-to-deploy"
delta = "0.21.1 -> 0.21.3"

[[audits.syn]]
who = "Oliver Hamlet <git@ortham.net>"
criteria = "safe-to-deploy"
delta = "2.0.106 -> 2.0.112"

[[trusted.libc]]
criteria = "safe-to-deploy"
user-id = 55123 # rust-lang-owner
start = "2024-08-15"
end = "2026-09-28"

[[trusted.windows-link]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2024-07-17"
end = "2026-09-28"
notes = "kennykerr is on the Windows team at Microsoft."

[[trusted.windows-result]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2024-02-02"
end = "2026-09-28"
notes = "kennykerr is on the Windows team at Microsoft."

[[trusted.windows-sys]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2021-11-15"
end = "2026-09-28"
notes = "kennykerr is on the Windows team at Microsoft."
