
# cargo-vet audits file

[[audits.codespan-reporting]]
who = "Oliver Hamlet <git@ortham.net>"
criteria = "safe-to-deploy"
delta = "0.12.0 -> 0.13.1"

[[audits.convert_case]]
who = "Oliver Hamlet <git@ortham.net>"
criteria = "safe-to-deploy"
delta = "0.8.0 -> 0.10.0"

[[audits.ctor]]
who = "Oliver Hamlet <git@ortham.net>"
criteria = "safe-to-deploy"
delta = "0.4.2 -> 0.6.3"

[[audits.ctor-proc-macro]]
who = "Oliver Hamlet <git@ortham.net>"
criteria = "safe-to-deploy"
delta = "0.0.5 -> 0.0.7"

[[audits.cxx]]
who = "Oliver Hamlet <git@ortham.net>"
criteria = "safe-to-deploy"
delta = "1.0.161 -> 1.0.192"

[[audits.cxx-build]]
who = "Oliver Hamlet <git@ortham.net>"
criteria = "safe-to-deploy"
delta = "1.0.161 -> 1.0.192"

[[audits.cxxbridge-flags]]
who = "Oliver Hamlet <git@ortham.net>"
criteria = "safe-to-deploy"
delta = "1.0.161 -> 1.0.192"

[[audits.cxxbridge-macro]]
who = "Oliver Hamlet <git@ortham.net>"
criteria = "safe-to-deploy"
delta = "1.0.161 -> 1.0.192"

[[audits.dtor]]
who = "Oliver Hamlet <git@ortham.net>"
criteria = "safe-to-deploy"
delta = "0.0.6 -> 0.1.1"

[[audits.dtor-proc-macro]]
who = "Oliver Hamlet <git@ortham.net>"
criteria = "safe-to-deploy"
delta = "0.0.5 -> 0.0.6"

[[audits.libloading]]
who = "Oliver Hamlet <git@ortham.net>"
criteria = "safe-to-deploy"
delta = "0.8.6 -> 0.8.9"
notes = "Mostly formatting changes, plus swaps windows-targets for windows-link, and adds a new function that looks fine."

[[audits.libloading]]
who = "Oliver Hamlet <git@ortham.net>"
criteria = "safe-to-deploy"
delta = "0.8.9 -> 0.9.0"

[[audits.libloadorder]]
who = "Oliver Hamlet <git@ortham.net>"
criteria = "safe-to-deploy"
version = "18.5.1"
notes = "This is my own crate published using Trusted Publishing, but I can't mark it as trusted by cargo-vet because it doesn't support Trusted Publishing and just sees that the publisher is unknown."

[[audits.link-cplusplus]]
who = "Oliver Hamlet <git@ortham.net>"
criteria = "safe-to-deploy"
delta = "1.0.10 -> 1.0.12"

[[audits.log]]
who = "Oliver Hamlet <git@ortham.net>"
criteria = "safe-to-deploy"
delta = "0.4.28 -> 0.4.29"

[[audits.loot-condition-interpreter]]
who = "Oliver Hamlet <git@ortham.net>"
criteria = "safe-to-deploy"
version = "5.3.3"
notes = "This is my own crate published using Trusted Publishing, but I can't mark it as trusted by cargo-vet because it doesn't support Trusted Publishing and just sees that the publisher is unknown."

[[audits.loot-condition-interpreter]]
who = "Oliver Hamlet <git@ortham.net>"
criteria = "safe-to-deploy"
delta = "5.3.3 -> 5.4.0"
notes = "This is my own crate published using Trusted Publishing, but I can't mark it as trusted by cargo-vet because it doesn't support Trusted Publishing and just sees that the publisher is unknown."

[[audits.napi]]
who = "Oliver Hamlet <git@ortham.net>"
criteria = "safe-to-run"
delta = "3.1.6 -> 3.8.1"

[[audits.napi]]
who = "Oliver Hamlet <git@ortham.net>"
criteria = "safe-to-deploy"
delta = "3.8.1 -> 3.8.2"

[[audits.napi-build]]
who = "Oliver Hamlet <git@ortham.net>"
criteria = "safe-to-deploy"
delta = "2.2.3 -> 2.3.1"

[[audits.napi-derive]]
who = "Oliver Hamlet <git@ortham.net>"
criteria = "safe-to-deploy"
delta = "3.2.2 -> 3.5.0"

[[audits.napi-derive-backend]]
who = "Oliver Hamlet <git@ortham.net>"
criteria = "safe-to-deploy"
delta = "2.1.2 -> 5.0.0"

[[audits.napi-sys]]
who = "Oliver Hamlet <git@ortham.net>"
criteria = "safe-to-deploy"
delta = "3.0.0 -> 3.2.1"

[[audits.regress]]
who = "Oliver Hamlet <git@ortham.net>"
criteria = "safe-to-deploy"
delta = "0.10.4 -> 0.10.5"

[[audits.slab]]
who = "Oliver Hamlet <git@ortham.net>"
criteria = "safe-to-deploy"
delta = "0.4.8 -> 0.4.11"

[[trusted.futures-task]]
criteria = "safe-to-deploy"
user-id = 33035 # Taiki Endo (taiki-e)
start = "2019-07-29"
end = "2027-01-06"
notes = "taiki-e is a member of the rust-lang GitHub org and of the Rust language's async working group, and the source repo is owned by the rust-lang GitHub org."

[[trusted.futures-util]]
criteria = "safe-to-deploy"
user-id = 33035 # Taiki Endo (taiki-e)
start = "2020-10-05"
end = "2027-01-06"
notes = "taiki-e is a member of the rust-lang GitHub org and of the Rust language's async working group, and the source repo is owned by the rust-lang GitHub org."

[[trusted.libc]]
criteria = "safe-to-deploy"
user-id = 55123 # rust-lang-owner
start = "2024-08-15"
end = "2026-09-28"
notes = "rust-lang-owner is a bot managed by the Rust language's infrastructure team, and the source repo is owned by the rust-lang GitHub org."

[[trusted.windows-link]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2024-07-17"
end = "2026-09-28"
notes = "kennykerr is on the Windows team at Microsoft."

[[trusted.windows-result]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2024-02-02"
end = "2026-09-28"
notes = "kennykerr is on the Windows team at Microsoft."

[[trusted.windows-sys]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2021-11-15"
end = "2026-09-28"
notes = "kennykerr is on the Windows team at Microsoft."
