[package]
name = "parameterized-test"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
proc-macro2 = "1.0.95"
quote = "1.0.40"
syn = { version = "2.0.100", features = ["full"] }

[lib]
proc-macro = true
